export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const SERVER_ERROR = 'SERVER_ERROR';

export const SAVE_PROFILE = 'EDIT_PROFILE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const CREATE_DB_PROFILE = 'CREATE_DB_PROFILE';
export const CREATE_DB_PROFILE_SUCCESS = 'CREATE_DB_PROFILE_SUCCESS';

export const FETCH_USER_CURRENCY_DIALS = 'FETCH_USER_CURRENCY_DIALS';
export const FETCH_USER_CURRENCY_DIALS_REQUEST =
  'FETCH_USER_CURRENCY_DIALS_REQUEST';
export const FETCH_USER_CURRENCY_DIALS_SUCCESS =
  'FETCH_USER_CURRENCY_DIALS_SUCCESS';
export const FETCH_USER_CURRENCY_DIALS_ERROR =
  'FETCH_USER_CURRENCY_DIALS_ERROR';

export const RECIVE_USER_CURRENCY_DIALS = 'RECIVE_USER_CURRENCY_DIALS';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_DATA = 'GET_USER_DATA';
export const RECIVE_ALL_USERS = 'RECIVE_ALL_USERS';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const SET_FILTER = 'SET_FILTER';

export const SIGNIN = 'SIGNIN';
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const SIGN_OUT = 'SIGN_OUT';

export const LOAD_CURRENCY = 'LOAD_CURRENCY';
export const LOAD_CURRENCY_REQUEST = 'LOAD_CURRENCY_REQUEST';
export const LOAD_CURRENCY_SUCCESS = 'LOAD_CURRENCY_SUCCESS';
export const LOAD_CURRENCY_ERROR = 'LOAD_CURRENCY_ERROR';
export const COUNT_CURRENCY = 'COUNT_CURRENCY';
export const COUNT_CURRENCY_ASYNC = 'COUNT_CURRENCY_ASYNC';
export const SWAP_CURRENCY = 'SWAP_CURRENCY';
export const SEND_DEAL = 'SEND_DEAL';
export const SEND_DEAL_POST = 'SEND_DEAL_POST';
export const SEND_DEAL_SUCCESS = 'SEND_DEAL_SUCCESS';
export const SEND_DEAL_ERROR = 'SEND_DEAL_ERROR';
