export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const SERVER_ERROR = 'SERVER_ERROR';

export const SAVE_PROFILE = 'EDIT_PROFILE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const GET_USER_CURRENCY_DIALS = 'GET_USER_CURRENCY_DIALS';
export const FETCH_USER_CURRENCY_DIALS = 'FETCH_USER_CURRENCY_DIALS';
export const RECIVE_USER_CURRENCY_DIALS = 'RECIVE_USER_CURRENCY_DIALS';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_DATA = 'GET_USER_DATA';
export const RECIVE_ALL_USERS = 'RECIVE_ALL_USERS';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const SET_FILTER = 'SET_FILTER';

export const LOAD_CURRENCY = 'LOAD_CURRENCY';
export const LOAD_CURRENCY_SUCCESS = 'LOAD_CURRENCY_SUCCESS';
export const LOAD_CURRENCY_FAILURE = 'LOAD_CURRENCY_FAILURE';
export const COUNT_CURRENCY = 'COUNT_CURRENCY';
export const COUNT_CURRENCY_ASYNC = 'COUNT_CURRENCY_ASYNC';
export const SWAP_CURRENCY = 'SWAP_CURRENCY';
export const SEND_DIAL = 'SEND_DIAL';
