export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const SERVER_ERROR = 'SERVER_ERROR';

export const SAVE_PROFILE = 'EDIT_PROFILE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const TABLE_GET_USER_DATA = 'TABLE_GET_USER_DATA';
export const TABLE_FETCH_USER_DATA = 'TABLE_FETCH_USER_DATA';
export const TABLE_RECIVE_USER_DATA = 'TABLE_RECIVE_USER_DATA';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_DATA = 'GET_USER_DATA';
export const RECIVE_ALL_USERS = 'RECIVE_ALL_USERS';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
